### ISSUE TITLE
secrets.yml file must be committed to repo to update via capistrano?

### ISSUE THREAD

**Issue by glenpierce** [consul/installer#128]
In the consul repo, there exists a file  config/secrets.yml.example which contains several placeholders for secrets:
twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
It appears that the only way to get these values updated is to create a new file:
config/secrets.yml
and then commit that file to a repository from which the installer can pull. This does not seem like a safe approach at all. Is there another way to pass these secrets into a production install of Consul?

**Comment by microweb10** [comment]
Hi @glenpierce,

It is not recommended to commit your personal secrets to a public repository. That's why the file `config/secrets.yml` is outside of the version control.

This installer already takes care of creating the file `config/secrets.yml`, so you don't have to do anything manually 😉 

After installation is complete, if any instance of CONSUL needs to adjust their secrets, they can easily do it by connecting to the production server and adjusting the file manually.

I hope this answers your question ☺️

**Comment by glenpierce** [comment]
That makes sense. Do I restart the Rails server after that?
According to this post: https://stackoverflow.com/questions/13655792/how-to-stop-and-restart-the-rails-server I'd run this command:
rails restart
Is that correct?

**Comment by microweb10** [comment]
Hi, the recommended and preferred way to restart the server in production is by using `capistrano`. You can run:
```
cap production deploy:restart
```
It will restart the server without doing any actual deployment. 😄 

Why would you prefer to do it from the server? 🤔

**Comment by glenpierce** [comment]
When I try 
`cap production deploy:restart`
I get `command not found` also, I don't have access to a machine that can run Ansible much of the time, but I can SSH into the server whenever I need to.

Thanks for taking the time to help me out with this. I'm volunteering for a very small municipality.

**Comment by javierm** [comment]
Hi @glenpierce. Thanks for volunteering to setup CONSUL :smile:. We're volunteers too :wink:.

We strongly recommend you [setup capistrano on your local machine](https://github.com/consul/installer#deploys-with-capistrano) and use it to deploy code to your server.

If you decide to handle things on the server, go ahead, but please understand in this case we cannot offer support for every possible scenario you run into :pray:. If you insist on restarting puma manually, have a look at `pumactl`, for example on this article about [Digesting pumactl](http://ruby-journal.com/digesting-pumactl/), or check [how capistrano-puma restarts puma](https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/tasks/puma.rake#L59). If you follow this path and run into any problems while trying to do so, I'm afraid there's a good chance we won't be able to help and you'll have to ask in general devops forums like stackoverflow.

**Comment by microweb10** [comment]
Closing this issue since this is not really an issue/bug with the installer ☺️ 

Also not the best way to get help or support 😉 

@glenpierce please note that you can use [CONSUL community](https://community.consulproject.org/), [CONSUL Gitter channel](https://gitter.im/consul/consul), or CONSUL Slack channel (if you provide your email we can add you to the Slack channel) where you can ask technical questions.

**Comment by javierm** [comment]
@glenpierce By the way, I've just realized somthing:

>rails restart isn't a recognized command on the server at this point.

I think you probably meant `bin/rails restart` :thinking: (assuming you're inside `~/consul/current/`)
