### ISSUE TITLE
TASK  Import GPG keys from keyservers error  time expired

### ISSUE THREAD

**Issue by mauroprosperi** [consul/installer#133]
[link to the code](https://github.com/consul/installer/blob/6ac86c064f08b959faeecd47f1733cca0baeae0a/galaxy/rvm.ruby/tasks/rvm.yml#L25)

### Error

> failed: [10.3.0.27] (item=hkp://pool.sks-keyservers.net) => changed=false 
>   ansible_loop_var: item
>   cmd: gpg --batch --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
>   delta: '0:01:30.618104'
>   end: '2019-11-14 17:45:33.117499'
>   item: hkp://pool.sks-keyservers.net
>   msg: non-zero return code
>   rc: 2
>   start: '2019-11-14 17:44:02.499395'
>   stderr: 'gpg: recepción del servidor de claves fallida: Expiró el tiempo de conexión'
>   stderr_lines: <omitted>
>   stdout: ''
>   stdout_lines: <omitted>

### Solution
The problem can be easily solved if you add the port to the link; `hkp://pool.sks-keyservers.net:80` on the code

**Comment by javierm** [comment]
It looks like it was a coincidence and the task timed out due to connectivity issues not related to changing the port :thinking:.

Note the code inside the `galaxy/rvm.ruby` is taken from the [rvm1-ansible](https://github.com/rvm/rvm1-ansible/) project, so maybe you can have a look at [rvm1-ansible issues](https://github.com/rvm/rvm1-ansible/issues) and report it if the problem persists and it hasn't already been reported :pray:.
