### ISSUE TITLE
Email setting tutorial - Errno::ECONNREFUSED in Devise::PasswordsController#create

### ISSUE THREAD

**Issue by bloomingmath** [consul/installer#139]
Trying the installer walkthrough, got stuck on email server setting. Tried in remote production and in local development get (I think) the same error. Using sendgrid and digitalocean production server.

This is how I changed secrets.yml in local development. Similar setting in the production section of secrets.yml in the remote server.
```
default: &default
  secret_key_base: *******
  # email_interceptor_recipients: ""
  server_name: "localhost"
  mailer_delivery_method: "smtp"
  smtp_settings:
    address:              "smtp.sendgrid.net"
    port:                 "587"
    domain:               "localhost"
    host:                 "smtp.sendgrid.net"
    user_name:            "apikey"
    password:             "*****"
    authentication:       "plain"
    enable_starttls_auto: true
```

This is the error that local development give:
[Action Controller_ Exception caught.pdf](https://github.com/consul/installer/files/3906522/Action.Controller_.Exception.caught.pdf)

**Comment by javierm** [comment]
Hi, @bloomingmath :smile:. Just to be sure, on production, did you restart the application after changing the secrets file?

Regarding local development, I'm a bit puzzled because by default in the development environment the SMTP settings are ignored and `letter_opener` is used to open emails :thinking:. Have you changed the `config/environments/development.rb` file? If not, what command do you use to start the sever in local development?

By the way, I assume on production you're replacing `domain: localhost` with your real domain, right? :thinking:

**Comment by javierm** [comment]
Hi, @bloomingmath :smile:. Just to be sure, on production, did you restart the application after changing the secrets file?

Regarding local development, I'm a bit puzzled because by default in the development environment the SMTP settings are ignored and `letter_opener` is used to open emails :thinking:. Have you changed the `config/environments/development.rb` file? If not, what command do you use to start the sever in local development?

By the way, I assume on production you're replacing `domain: localhost` with your real domain, right? :thinking: Same with the `server_name`.

**Comment by bloomingmath** [comment]
Hi!
When I deploy changes with capistrano or when I change some files directly on the remote server, I restart with `cap production deploy:restart`.
I changed the local development because, getting a 500 error page and not much more on log/production.log I was hoping the development environment could give me more debug information. So I changed the default settings (which was working, opening an "email" in the browser) to reproduce locally the error I get in production.
Locally I run the server with `bin/rails s`; remotely I have no idea what happen, just what the installer set up.
On production `domain` and `server_name` are both set to "167.99.174.84" which is the actual ip DigitalOcean gave me.

**Comment by javierm** [comment]
I see. One of the causes of the error in development might be using `localhost` in the secrets file, since the error message says it can't connect to localhost on port 25 :thinking:.

Would it be possible for you to search for the error you're getting when trying to send emails on your production server? The logs are in the `consul/current/log/` folder.

**Comment by bloomingmath** [comment]
Sure. Meanwhile thanks for your help: I have never used rails nor ruby and this task of setting of Consul is bigger than me. Unfortunately here in Chile we are in the middle of a crisis and I hope that this platform can help us with the dialogue at town level.

Here is the log produced when asking for a new password
[development.log](https://github.com/consul/installer/files/3907705/development.log)

**Comment by javierm** [comment]
Could you go to your `consul/current` folder on your production server and execute `bin/rails c production`? That opens a Rails console. In that console, could you run the following commands and tell us the output of each of them (but hide usernames and passwords before pasting the output here, of course :wink:)?

```
ActionMailer::Base.smtp_settings
Rails.application.secrets.smtp_settings
ActionMailer::Base.delivery_method
```

**Comment by bloomingmath** [comment]
Here is the log. 
[railsconsole.log](https://github.com/consul/installer/files/3908264/railsconsole.log)

**Comment by javierm** [comment]
The only unusual thing I notice is strings are used instead of symbols :thinking:.

Can you try editing your `secrets.yml`?

1. Replace `"smtp"` with `:smtp` (that is, remove the double quotes and add a colon)
2. Prefix with `:` every key in the `smtp_settings:`, except the line saying `smtp_settings:`. Something like:
```
  smtp_settings:
    :address: "smtp.sendgrid.net"
    :port: 587
    :domain: "167.99.174.84"
    :user_name: "apikey"
    :password: "***"
    :authentication: "plain"
    :enable_starttls_auto: true
```

Then restart the application, test it again, and if it doesn't work, open again a Rails console and paste the results of:

```
ActionMailer::Base.smtp_settings
Rails.application.secrets.smtp_settings
ActionMailer::Base.delivery_method
```

And check the production log again to be sure the error isn't a different one.

Thanks!

**Comment by bloomingmath** [comment]
Well thanks to you! It work now in development and in production too. Thank you for your help and for your job with consul.
