### ISSUE TITLE
Dockerized deployment

### ISSUE THREAD

**Issue by pocman** [consul/installer#93]
Hi all,
Thanks for the good work. 
I'm used to deploying docker images in production (AWS or CleverCloud) and to have a docker-compose file similar to my production env (1 postgresql and at least 2 app instances).
I'm a bit lost in this setup.

Do you know if someone is working on a production docker image of consul ?
I guess, we would need a way to enable cron and emails sender on only one instance.
To create and migrate automatically the database schema/data.

Regards, 
Thomas.

**Comment by PierreMesure** [comment]
Hey @pocman! Welcome! Yes, a team worked on dockerizing Consul over a year ago and some organisations are still maintaining a Docker version for their own use.

There is a [docker-compose](https://github.com/consul/consul/blob/master/docker-compose.yml) for CONSUL but I doubt it works right now because no one has updated it in a long time. Maybe you could have a look at it and fix what needs to be?

I think @vanessametonini would be interested to hear about it as well.

**Comment by javierm** [comment]
Hi, @pocman :smile:.

Sorry for the late reply :pray:; development in this repository is particularly slow :sweat_smile:.

You can check our documentation about [setting up CONSUL with Docker](https://docs.consulproject.org/docs/english-documentation/introduction/servers/docker). If you've got more specific questions, feel free to ask! :wink:
